version: '3.9'
services:
  gildedrosedb:
    image: 'postgres:13.3-buster'
    volumes:
      - './database/migrations:/docker-entrypoint-initdb.d'
      - './database/postgres-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '${POSTGRES_HOST_PORT}:5432'
  gildedroseapi:
    build:
      context: ./api/
      dockerfile: Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_URLS2=${ASPNETCORE_URLS}
    depends_on:
      - gildedrosedb
    ports:
    - '${API_HOST_PORT}:80'
  gildedroseapp:
    build:
      context: ./app/
      dockerfile: Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_URLS2=${ASPNETCORE_URLS}
    depends_on:
      - gildedroseapi
    ports:
      - '${APP_HOST_PORT}:80'